"""create jobs table

Revision ID: 7bbd7e54b5c8
Revises: 
Create Date: 2025-02-08 08:13:29.972480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bbd7e54b5c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'PENDING', 'SCHEDULED', 'RUNNING', 'COMPLETED', 'FAILED', 'PREEMPTED', name='jobstatusenum'), nullable=False),
    sa.Column('job_metadata', sa.String(), nullable=False),
    sa.Column('last_status_change', sa.DateTime(timezone=True), nullable=False),
    sa.Column('preemption_count', sa.Integer(), nullable=True),
    sa.Column('wait_time_weight', sa.Float(), nullable=True),
    sa.Column('leader_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
